### ISSUE TITLE
Sistema de diseño

### ISSUE THREAD

**Issue by berehc** [berehc/BarreApp-client#3]

**Comment by sofiagraves** [comment]
https://colorhunt.co/palette/64384399627ac88ea7e7cbcb
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/142c8363-3da5-446c-9eb2-bc8b63b0c0de">

**Comment by sofiagraves** [comment]
https://colorhunt.co/palette/331d2c3f2e3ea78295efe1d1
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/192ae38a-0e28-42ea-8dce-665d8ec5723a">

**Comment by sofiagraves** [comment]
https://colorhunt.co/palette/fff8ea9e7676815b5b594545
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/3fb7c3af-5928-4ac1-853f-000f5b712c67">

**Comment by sofiagraves** [comment]
https://colorhunt.co/palette/635985443c6839305318122b
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/6c484277-f9a7-4e99-9550-421a4d885bfb">

**Comment by sofiagraves** [comment]
https://colorhunt.co/palette/9a3b3bc08261e2c799f2ecbe
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/cfa311b4-02b1-4d5d-ac14-5357a0c96af1">

**Comment by sofiagraves** [comment]
https://fonts.google.com/specimen/Poppins
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/aae176f8-dd55-44b3-9da3-d80d9cc49658">

**Comment by sofiagraves** [comment]
https://fonts.google.com/specimen/Barlow
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/00acc1f7-582c-4da3-8ec5-c41bccfc9246">

**Comment by sofiagraves** [comment]
https://fonts.google.com/specimen/Work+Sans
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/e8604ede-a350-472b-b5a9-6746528179c1">

**Comment by sofiagraves** [comment]
hay muchas fotos en este estudio si buscas barre hahahha
https://www.pexels.com/photo/ethnic-female-ballet-tutor-practicing-stretch-with-girl-5150538/
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/2a0014d6-762a-41df-9d20-1a6712873877">

**Comment by berehc** [comment]
Una idea de logotipo: 

![Image](https://github.com/berehc/BarreApp-client/assets/144291246/5fd26f97-2e01-4deb-a617-dcff4580b793)

**Comment by berehc** [comment]
Otra idea:


![Image](https://github.com/berehc/BarreApp-client/assets/144291246/cb025dd4-1f95-4a21-9995-ce51225f1ebd)

**Comment by berehc** [comment]
![Image](https://github.com/berehc/BarreApp-client/assets/144291246/e09d7236-cbc0-48ca-b10f-6850a688e1cb)

**Comment by sofiagraves** [comment]
https://www.pexels.com/photo/graceful-positive-asian-teacher-and-little-ballerina-stretching-together-5150507/
<img width="960" alt="image" src="https://github.com/berehc/BarreApp-client/assets/139278851/94e8800e-8a59-4354-9083-001c4002d843">
